<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gtpl</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{(template|if|foreach|literal|Call|Yield)(([^{]|\{([^{]|\{([^{]|\{[^{}]*?\})*?\})*?\})*?)?\}</string>
	<key>foldingStopMarker</key>
	<string>\{/(template|if|foreach|literal|Call|Yield)\}</string>
	<key>name</key>
	<string>GTPL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#gtpl_comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\{)(namespace)\s*([a-zA-Z0-9._\-]+)\s*(\})</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.gtpl.brace</string>
				</dict>
				<key>2</key>
			 		<dict>
						<key>name</key>
						<string>keyword.gtpl</string>
			  		</dict>
			 	<key>3</key>
			 	<dict>
					<key>name</key>
					<string>support.gtpl.templatename</string>
			  	</dict>
				<key>4</key>
			  	<dict>
					<key>name</key>
					<string>punctuation.definition.gtpl.brace</string>
				</dict>
			</dict>
			<key>name</key>
			<string>tag.gtpl.namespace</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{)(template)\s*([a-zA-Z0-9._\-]+)\s*(\})</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.gtpl.brace</string>
				</dict>
				<key>2</key>
			 		<dict>
						<key>name</key>
						<string>keyword.gtpl</string>
			  		</dict>
			 	<key>3</key>
			 	<dict>
					<key>name</key>
					<string>support.gtpl.templatename</string>
			  	</dict>
				<key>4</key>
			  	<dict>
					<key>name</key>
					<string>punctuation.definition.gtpl.brace</string>
				</dict>
			</dict>

			<key>end</key>
			<string>(\{\/)(template)\s*(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.gtpl.brace</string>
				</dict>
				<key>2</key>
			 		<dict>
						<key>name</key>
						<string>keyword.gtpl</string>
			  		</dict>
				<key>3</key>
			  	<dict>
					<key>name</key>
					<string>punctuation.definition.gtpl.brace</string>
				</dict>
			</dict>

			<key>contentName</key>
			<string>meta.gtpl.template</string>

			<key>patterns</key>
			<array>
			  <dict>
					<key>include</key>
					<string>#gtpl_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#gtpl_tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html_tag</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>html_string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.gtpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.gtpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.gtpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#gtpl_tag</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>gtpl_tag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\{\/?)(\b(template|if|elseif|else|foreach|break|continue|call|Call|yield|Yield|param|container|meta|ifempty|cycle|namespace|literal|ldelim|rdelim)\b)?(([^{]|\{([^{]|\{([^{]|\{[^{}]*?\})*?\})*?\})*?)?(\})</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.gtpl.brace</string>
						</dict>	
						<key>2</key>
					 	<dict>
							<key>name</key>
							<string>keyword.gtpl</string>
		  				</dict>
		 				<key>4</key>
		 				<dict>
							<key>name</key>
							<string>support.gtpl.expression</string>
			  			</dict>
						<key>8</key>
			  			<dict>
							<key>name</key>
							<string>punctuation.definition.gtpl.brace</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.gtpl.tag</string>
				</dict>
			</array>
		</dict>
		<key>html_comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;\!\-\-</string>
					<key>contentName</key>
					<string>commment.block.preprocessor</string>
					<key>end</key>
					<string>\-\-&gt;</string>
					<key>name</key>
					<string>comment.block.html</string>
				</dict>
			</array>
		</dict>
		<key>html_tag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;\/?)([a-zA-Z0-9]+)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.gtpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.gtpl</string>
						</dict>

					</dict>
					<key>end</key>
					<string>&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.gtpl</string>
						</dict>
					</dict>

					<key>name</key>
					<string>entity.tag.gtpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#gtpl_tag</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#html_string</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>gtpl_comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{\*</string>
					<key>contentName</key>
					<string>comment.block.preprocessor</string>
					<key>end</key>
					<string>\*\}</string>
					<key>name</key>
					<string>comment.block.gtpl</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.gtpl</string>
	<key>uuid</key>
	<string>C56846DE-CB9A-4DB5-9D38-DC417DEA4D5E</string>
</dict>
</plist>
